### ISSUE TITLE
USER STORY: Build CMS for Manual Updates

### ISSUE THREAD

**Issue by OSawani** [OSawani/Application-Manual-Zinc-Flake#4]
As an **admin** I want to  **update manual content** so that **the information stays current**

## Acceptance Criteria:
* The CMS allows for text updates without needing developer intervention.
* Changes in the CMS are reflected on the web app immediately.
## Tasks:
- [ ] **Rich Text Editor Configuration**: Set Up a rich text editor to enable content managers to easily add, update or delete text and images, ensuring role-based access.  
- [ ] **Content CRUD Operations**: Develop backend APIs for creating, reading, updating, and deleting conent entries. 
- [ ] **Role-Based Acess Control**: Set Up access levels in the rich text editor to differentiate between roles.
